/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

module pes_brg(clk, reset, sel, clkout);
  wire [5:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire [3:0] _151_;
  wire [3:0] _152_;
  wire [1:0] _153_;
  wire [1:0] _154_;
  wire [2:0] _155_;
  wire [2:0] _156_;
  input clk;
  wire clk;
  output clkout;
  reg clkout;
  reg [5:0] cnt1 = 6'h00;
  reg [1:0] cnt2 = 2'h0;
  reg [2:0] cnt3 = 3'h0;
  reg [3:0] cnt4 = 4'h0;
  input reset;
  wire reset;
  input [1:0] sel;
  wire [1:0] sel;
  sky130_fd_sc_hd__clkinv_1 _157_ (
    .A(_119_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__clkinv_1 _158_ (
    .A(_116_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(_117_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__clkinv_1 _160_ (
    .A(_114_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _161_ (
    .A(_107_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(_119_),
    .B(_120_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__and4b_1 _163_ (
    .A_N(_121_),
    .B(_122_),
    .C(_119_),
    .D(_120_),
    .X(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(_150_),
    .B(_149_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__or3_1 _165_ (
    .A(_148_),
    .B(_125_),
    .C(_126_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _166_ (
    .A(_109_),
    .B(_111_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor3b_1 _167_ (
    .A(_110_),
    .B(_112_),
    .C_N(_113_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand3_1 _168_ (
    .A(_108_),
    .B(_127_),
    .C(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a31oi_1 _169_ (
    .A1(_108_),
    .A2(_127_),
    .A3(_128_),
    .B1(_148_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_150_),
    .B(_149_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__and2_0 _171_ (
    .A(_148_),
    .B(_131_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _172_ (
    .A(_148_),
    .B(_131_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _173_ (
    .A1(_126_),
    .A2(_133_),
    .B1(_130_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21ai_0 _174_ (
    .A1(_150_),
    .A2(_149_),
    .B1(_148_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2b_1 _175_ (
    .A_N(_149_),
    .B(_150_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _176_ (
    .A1(_130_),
    .A2(_134_),
    .B1(_133_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2b_1 _177_ (
    .A_N(_150_),
    .B(_149_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _178_ (
    .A1(_130_),
    .A2(_135_),
    .B1(_133_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a311o_1 _179_ (
    .A1(_116_),
    .A2(_123_),
    .A3(_118_),
    .B1(_134_),
    .C1(_148_),
    .X(_095_)
  );
  sky130_fd_sc_hd__a211o_1 _180_ (
    .A1(_115_),
    .A2(_102_),
    .B1(_135_),
    .C1(_148_),
    .X(_096_)
  );
  sky130_fd_sc_hd__a31oi_1 _181_ (
    .A1(_094_),
    .A2(_095_),
    .A3(_096_),
    .B1(_129_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(_130_),
    .B(_136_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(_108_),
    .B(_132_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(_129_),
    .B(_133_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(_108_),
    .B(_109_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_137_),
    .B(_138_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__and3_1 _187_ (
    .A(_108_),
    .B(_109_),
    .C(_110_),
    .X(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _188_ (
    .A1(_108_),
    .A2(_109_),
    .B1(_110_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor3_1 _189_ (
    .A(_132_),
    .B(_139_),
    .C(_140_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and4_1 _190_ (
    .A(_108_),
    .B(_109_),
    .C(_111_),
    .D(_110_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(_111_),
    .B(_139_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor3_1 _192_ (
    .A(_132_),
    .B(_141_),
    .C(_142_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(_112_),
    .B(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(_112_),
    .A2(_141_),
    .B1(_133_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21oi_1 _195_ (
    .A1(_112_),
    .A2(_141_),
    .B1(_144_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xor2_1 _196_ (
    .A(_113_),
    .B(_143_),
    .X(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_137_),
    .B(_145_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xor2_1 _198_ (
    .A(_116_),
    .B(_117_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_116_),
    .B(_117_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xnor2_1 _200_ (
    .A(_118_),
    .B(_146_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xor2_1 _201_ (
    .A(_115_),
    .B(_114_),
    .X(_103_)
  );
  sky130_fd_sc_hd__xor2_1 _202_ (
    .A(_119_),
    .B(_120_),
    .X(_099_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(_121_),
    .B(_124_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand3_1 _204_ (
    .A(_119_),
    .B(_120_),
    .C(_121_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xnor2_1 _205_ (
    .A(_122_),
    .B(_147_),
    .Y(_101_)
  );
  always @(posedge clk)
    if (_001_)
      if (_006_) cnt4[0] <= 1'h0;
      else cnt4[0] <= _151_[0];
  always @(posedge clk)
    if (_001_)
      if (_006_) cnt4[1] <= 1'h0;
      else cnt4[1] <= _152_[1];
  always @(posedge clk)
    if (_001_)
      if (_006_) cnt4[2] <= 1'h0;
      else cnt4[2] <= _152_[2];
  always @(posedge clk)
    if (_001_)
      if (_006_) cnt4[3] <= 1'h0;
      else cnt4[3] <= _152_[3];
  always @(posedge clk)
    if (_005_)
      if (reset) clkout <= 1'h0;
      else clkout <= _082_;
  always @(posedge clk)
    if (_004_) cnt1[0] <= _000_[0];
  always @(posedge clk)
    if (_004_) cnt1[1] <= _000_[1];
  always @(posedge clk)
    if (_004_) cnt1[2] <= _000_[2];
  always @(posedge clk)
    if (_004_) cnt1[3] <= _000_[3];
  always @(posedge clk)
    if (_004_) cnt1[4] <= _000_[4];
  always @(posedge clk)
    if (_004_) cnt1[5] <= _000_[5];
  always @(posedge clk)
    if (_003_)
      if (_008_) cnt2[0] <= 1'h0;
      else cnt2[0] <= _153_[0];
  always @(posedge clk)
    if (_003_)
      if (_008_) cnt2[1] <= 1'h0;
      else cnt2[1] <= _154_[1];
  always @(posedge clk)
    if (_002_)
      if (_007_) cnt3[0] <= 1'h0;
      else cnt3[0] <= _155_[0];
  always @(posedge clk)
    if (_002_)
      if (_007_) cnt3[1] <= 1'h0;
      else cnt3[1] <= _156_[1];
  always @(posedge clk)
    if (_002_)
      if (_007_) cnt3[2] <= 1'h0;
      else cnt3[2] <= _156_[2];
  assign _151_[3:1] = cnt4[3:1];
  assign _152_[0] = _151_[0];
  assign _153_[1] = cnt2[1];
  assign _154_[0] = _153_[0];
  assign _155_[2:1] = cnt3[2:1];
  assign _156_[0] = _155_[0];
  assign _119_ = cnt4[0];
  assign _151_[0] = _098_;
  assign _120_ = cnt4[1];
  assign _121_ = cnt4[2];
  assign _122_ = cnt4[3];
  assign _148_ = reset;
  assign _150_ = sel[1];
  assign _149_ = sel[0];
  assign _006_ = _094_;
  assign _116_ = cnt3[0];
  assign _155_[0] = _104_;
  assign _108_ = cnt1[0];
  assign _109_ = cnt1[1];
  assign _111_ = cnt1[3];
  assign _110_ = cnt1[2];
  assign _112_ = cnt1[4];
  assign _113_ = cnt1[5];
  assign _001_ = _089_;
  assign _004_ = _092_;
  assign _002_ = _090_;
  assign _003_ = _091_;
  assign _117_ = cnt3[1];
  assign _118_ = cnt3[2];
  assign _007_ = _095_;
  assign _115_ = cnt2[1];
  assign _114_ = cnt2[0];
  assign _008_ = _096_;
  assign _005_ = _093_;
  assign _000_[0] = _083_;
  assign _000_[1] = _084_;
  assign _000_[2] = _085_;
  assign _000_[3] = _086_;
  assign _000_[4] = _087_;
  assign _000_[5] = _088_;
  assign _107_ = clkout;
  assign _082_ = _097_;
  assign _153_[0] = _102_;
  assign _156_[1] = _105_;
  assign _156_[2] = _106_;
  assign _154_[1] = _103_;
  assign _152_[1] = _099_;
  assign _152_[2] = _100_;
  assign _152_[3] = _101_;
endmodule
